[package]
name = "indexer"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.1"
futures = "0.3.5"
tokio = { version = "1.28.2", features = ["sync", "time"] }
deadpool = "0.10.0"
lapin = "2.3.1"
deadpool-lapin = "0.11.0"
tokio-executor-trait = "2.1.0"
tokio-reactor-trait = "1.1.0"


clap = { version = "3.1.6", features = ["color", "derive", "env"] }
dotenv = "0.15.0"
humantime = "2.1.0"
itertools = "0.10.0"
openssl-probe = "0.1.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.68"

tracing = { version = "0.1.36", features = ["std"] }
thiserror = "1.0.56"
anyhow = "1.0.79"

near-indexer = { git = "https://github.com/near/nearcore", rev = "4fce209e78fd1008c3a779101d080fe1570bbfe9" }
near-client = { git = "https://github.com/near/nearcore", rev = "4fce209e78fd1008c3a779101d080fe1570bbfe9" }
near-o11y = { git = "https://github.com/near/nearcore", rev = "4fce209e78fd1008c3a779101d080fe1570bbfe9" }
near-client-primitives = { git = "https://github.com/near/nearcore", rev = "4fce209e78fd1008c3a779101d080fe1570bbfe9" }

[dev-dependencies]
near-crypto = { git = "https://github.com/near/nearcore", rev = "4fce209e78fd1008c3a779101d080fe1570bbfe9" }